# Configuration for the FeatUp Joint Bilateral Upsampler using MaskCLIP backbone

# Registry key for the upsampler class
name = "featup_jbu"

# Parameters passed to the JointBilateralUpsampler constructor
[params]
backbone_hub_id = "maskclip" # Identifier for torch.hub.load("mhamilton723/FeatUp", ...)
use_norm = false           # Whether to use the FeatUp variant with LayerNorm
target_size = 224         # Target input image size after padding 