# Configuration for the FeatUp Joint Bilateral Upsampler using DINOv1 ViT-S/16 backbone

# Registry key for the upsampler class
name = "featup_jbu"

# Parameters passed to the JointBilateralUpsampler constructor
[params]
backbone_hub_id = "dino16" # Identifier for torch.hub.load("mhamilton723/FeatUp", ...)
use_norm = true           # Whether to use the FeatUp variant with LayerNorm
target_size = 224         # Target input image size after padding 